version: '3.8'
services:
    backend:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - mysql
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ecommerce
            MYSQL_USER: ecommerce_user
            MYSQL_PASSWORD: secret
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    mysql-data:
